# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60e7c2c56e795cc50e37ae65bdad2bcf6033711a77b8f9bdf97165e005cb3682acbf74215d2a7bfc22a365ca0ecd360726a6f8f30e112fc5934d4e06bf30bc80

test:
  secret_key_base: 58fb2911bb033bdb694717610ec25b1f6b7be839a8e821977cd61da5406ca21b09ba5d758cf135ad4004d94d02b9784aece7a39c4584b1b98c391b069d012eb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
